### ISSUE TITLE
Unexpected output during execution: `wrong fixed counters count`, `kpc_set_config failed`

### ISSUE THREAD

**Issue by StephanSchmiedmayer** [Fraunhofer-AISEC/libpabc#2]
## Description

Program repeatedly outputs unexpected warnings, especially `wrong fixed counters count` and `kpc_set_config failed`. 
Causes the demo in the readme to fail since it gets included in the "JSON" variables. 

MacOS 14.0 (M1 Pro)

**Comment by StephanSchmiedmayer** [comment]
`kpc_set_config failed` can be fixed by running with `sudo` permissions (needed bc of `kperf`)

**Comment by schanzen** [comment]
We should open an issue in the relic repo for this

**Comment by StephanSchmiedmayer** [comment]
Fixed with dc8d67124e7c4cdc338883e0cb532727c462767f
